'use client'

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot_compressed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Solid1_5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_15.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_16.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_17.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_18.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_19.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_20.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_21.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_22.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_23.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_24.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_25.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_26.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_27.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_28.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_29.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_30.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_31.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid2_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_32.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_33.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_34.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_35.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_36.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_37.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_38.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid2_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_39.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_40.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_41.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_42.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_43.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_44.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_45.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_46.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_47.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid2_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid3_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid4_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid5_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid6_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid7_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid8_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid15.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid16.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid17.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_48.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_49.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_50.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_51.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_52.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_53.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_54.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_55.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_56.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_57.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_58.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_59.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_62.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid3_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid4_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid5_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid6_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid7_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid8_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid9_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid2_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_72.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_82.geometry}
        material={
          materials.XID_CarbonFiber1_89DA56309D004869A12FD4C19EED2FBB_shader
        }
      />
      <mesh
        geometry={nodes.Solid1_83.geometry}
        material={
          materials.XID_CarbonFiber1_89DA56309D004869A12FD4C19EED2FBB_shader
        }
      />
      <mesh
        geometry={nodes.Solid1_73.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1.geometry}
        material={
          materials.XID_CarbonFiber1_89DA56309D004869A12FD4C19EED2FBB_shader
        }
        position={[0, -0.1, 0.7]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Solid1_1.geometry}
        material={materials.PaletteMaterial001}
        position={[0.4, -0.1, 0.7]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Solid1_2.geometry}
        material={
          materials.XID_SteelBlue_06E992B9E0FA4C8AB0BD30902E924D31_shader
        }
        position={[0.2, -0.1, 0.3]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0}
      />
      <group
        position={[0.1, 0.1, 0.2]}
        rotation={[0, 0, Math.PI / 6]}
        scale={0}
      >
        <mesh
          geometry={nodes.Solid1_85.geometry}
          material={
            materials.XID_FineTexturedBlack_1DDD52DA2CCD4E6ABC0C575F55DE5771_shader
          }
        />
        <mesh
          geometry={nodes.Solid1_86.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.Solid1_4.geometry}
        material={materials.PaletteMaterial003}
        position={[0.2, 0.3, 0.5]}
        rotation={[-Math.PI, -0.2, -Math.PI]}
        scale={0}
      />
      <mesh
        geometry={nodes.Solid1_77.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_78.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_79.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_80.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_60.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_61.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_63.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_64.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_65.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_66.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_67.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_68.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_69.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_70.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid1_71.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid2_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Solid2_5.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  )
}

useGLTF.preload('/robot_compressed.glb')
